### ISSUE TITLE
Stops ingesting every 12 hours

### ISSUE THREAD

**Issue by frankvandenhurk** [kaareseras/node-red-contrib-kusto#2] opened 2022-08-10 10:33 UTC
I've been running this for a few days now, but it regularly stops ingesting (most times within 24h) without any notice. Output is still the number of messages it has been processed (this looks normal and stays normal) but without any notice no more data is showing up in Azure. When I press redeploy in node-red it starts working again. Any idea how to debug? I’m using the free Azure Data Explorer.

**Comment by frankvandenhurk** [comment] 2022-08-12 18:00
I created a little node to monitor ingested messages (https://github.com/frankvandenhurk/node-red-contrib-kusto-monitor), but still no idea how to find the cause of this problem. Maybe i'll try to automatically restart if if the last message is too old.

**Comment by frankvandenhurk** [comment] 2022-08-14 08:48
I have ingestion successfully running, but after a while it stops functioning and I get the following error for each request:


```
RestError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:342xxxxb-0003-0xx1-3cxxxxf4xx80xx000
Time:2022-08-13T18:20:44.7698771Z
 {
  "name": "RestError",
  "statusCode": 403,
  "request": {
    "streamResponseStatusCodes": {},
    "url": "https://xbwvirtualdms.queue.core.windows.net/kvcsxxxxxf7xxxxx5txxdz-aggregatorinput-secured-2/messages?sv=REDACTED&st=REDACTED&se=REDACTED&sp=REDACTED&sig=REDACTED&timeout=REDACTED",
    "method": "POST",
    "headers": {
      "_headersMap": {
        "content-type": "application/xml; charset=utf-8",
        "x-ms-version": "REDACTED",
        "user-agent": "azsdk-js-storagequeue/12.0.5 (NODE-VERSION v16.16.0; Linux 4.4.180+)",
        "x-ms-client-request-id": "9fxxxxxf-xxf3-x8x6-xxx9-34ac74xxxxxb",
        "cookie": "REDACTED"
      }
    },
    "withCredentials": false,
    "timeout": 0,
    "keepAlive": true,
    "requestId": "9fxxxxxf-xxf3-x8x6-xxx9-34ac74xxxxxb"
  },
  "details": {
    "requestId": "342xxxxb-0003-0xx1-3cxxxxf4xx80xx000",
    "date": "2022-08-13T18:20:44.000Z",
    "errorCode": "AuthenticationFailed",
    "content-length": "544",
    "content-type": "application/xml",
    "server": "Microsoft-HTTPAPI/2.0",
    "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:342xxxxb-0003-0xx1-3cxxxxf4xx80xx000\nTime:2022-08-13T18:20:44.7698771Z",
    "Code": "AuthenticationFailed",
    "AuthenticationErrorDetail": "Signature not valid in the specified time frame: Start [Sat, 13 Aug 2022 05:08:07 GMT] - Expiry [Sat, 13 Aug 2022 17:13:07 GMT] - Current [Sat, 13 Aug 2022 18:20:44 GMT]"
  },
  "message": "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:342xxxxb-0003-0xx1-3cxxxxf4xx80xx000\nTime:2022-08-13T18:20:44.7698771Z"
}

```

After restarting the service it functions properly again.

**Comment by kaareseras** [comment] 2022-08-15 07:38
Thank you for the testing and feedback, sorry for the delay, but I have been traveling. I will push the error to the DataExplorer team, to hear what the problem is.

**Comment by frankvandenhurk** [comment] 2022-08-15 16:35
Thank you for getting in contact with the DataExplorer team. 

Please note: I anonymised the logging bij replacing parts of the unique strings with x-es. If you want the original, or more logging, please let me know.

**Comment by frankvandenhurk** [comment] 2022-08-21 07:05
It looks like the problem comes almost exacly every 12 hours, so it looks like some authorisation token is non automatically refreshed where it should. Just restarting the application fixes the problem.

**Comment by kaareseras** [comment] 2022-08-21 07:27
> It looks like the problem comes almost exacly every 12 hours, so it looks like some authorisation token is non automatically refreshed where it should. Just restarting the application fixes the problem.

I see the same in my setup. However only on free ADX. On a normal paid cluster hvis is not an issue. Im in contact with the MS SDK team, looking for the bug.

**Comment by frankvandenhurk** [comment] 2022-08-21 08:04
I am using free ADX

**Comment by kaareseras** [comment] 2022-08-22 10:54
Released version 1.0.7. This have an update of the Kusto SDK. Please test

**Comment by frankvandenhurk** [comment] 2022-08-22 15:55
Tnx for the new version. Just upgraded tot 1.0.7 and restarted node-red. I'll keep an eye on the monitoring output and let you know.

**Comment by frankvandenhurk** [comment] 2022-08-23 05:48
I'm afraid that didn't help. Restarted a little before 18:00 yesterday, and this morning a little befor 6:00 the monitoring detected the problem.

**Comment by kaareseras** [comment] 2022-08-23 08:28
I see the same, I'll continue to work with the team.

**Comment by kaareseras** [comment] 2022-08-25 11:07
A bug was found in SDK, v.1.0.8 released, please test

**Comment by frankvandenhurk** [comment] 2022-08-25 15:50
Just updated, we'll know in 12 hours

**Comment by kaareseras** [comment] 2022-08-26 11:08
After the update to 1.0.8, the node is running without errors. closing issue
@frankvandenhurk  thank you for the help

**Closed as completed by kaareseras** 2022-08-26 11:08 UTC
